package ali;

import ali.controllers.BukuController;
import ali.controllers.DDCController;
import ali.models.BukuModel;
import ali.models.DDCModel;
import com.sun.org.apache.xalan.internal.xsltc.compiler.util.StringStack;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author om
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    
    private boolean isLoggin= false;
    private boolean isUpdate=false;
    private database db;
    private BukuController bukuC;
    private DDCController ddcC;
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModelD;
    public Desktop() {
        initComponents();
        db = new database();
        bukuC = new BukuController();
        ddcC = new DDCController();
        tableModel = (DefaultTableModel) jTableBuku.getModel();
        tableModelD = (DefaultTableModel) jTableDDC.getModel();
        fillBookTable();
        fillDDCTable();
    }
    
    private void fillBookTable(){
        try{
            ArrayList<BukuModel> books = bukuC.retrieveBooks();
            if(books.size() == 0)
                System.out.println("Buku Kosong");
            
            if(tableModel.getRowCount() > 0){
                for(int i = 0; i < tableModel.getRowCount(); i++)
                    tableModel.removeRow(i);
                tableModel.removeRow(0);
            }
            
            for(BukuModel b : books){
                tableModel.addRow(new String[]{b.getKode(), b.getJudul(), b.getPengarang(), b.getPenerbit(), b.getTanggalTerbit().toString(),
                b.getIsbn(), b.getEdisi(), b.getKolasi(), b.getJumlah(), b.getJumlah(), b.getHarga(), b.getDeskripsi()});
            }
            tableModel.fireTableDataChanged();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void fillUpdateBook(){
        try{
            ArrayList<BukuModel> books = bukuC.retrieveBooks();
            if(books.size() == 0)
                System.out.println("Buku Kosong");
            for(BukuModel b : books){
                jTextKodeBuku.setText(b.getKode());
//                tableModel.addRow(new String[]{b.getKode(), b.getJudul(), b.getPengarang(), b.getPenerbit(), b.getTanggalTerbit(),
//                b.getIsbn(), b.getEdisi(), b.getKolasi(), b.getJumlah(), b.getJumlah(), b.getHarga(), b.getDeskripsi()});
            }
            tableModel.fireTableDataChanged();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void fillDDCTable(){
        try{
            ArrayList<DDCModel> ddcs = ddcC.retiveDDCModels();
            if(ddcs.size() == 0)
                System.out.println("DDC Kosong");
            for(DDCModel d : ddcs){
                tableModelD.addRow(new String[]{d.getNomer_ddc(), d.getNama_ddc(),d.getDeskripsi()});
            }
            tableModelD.fireTableDataChanged();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Buku = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        jButtonInputBuku = new javax.swing.JButton();
        jButtonCariBuku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonHapusBuku = new javax.swing.JButton();
        jButtonUpdateBuku = new javax.swing.JButton();
        Peminjaman = new javax.swing.JPanel();
        Transaksi = new javax.swing.JPanel();
        jPanel_input_anggota = new javax.swing.JPanel();
        jPanel_input_buku = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelInputBuku = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextKodeBuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextJudulBuku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextPengarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextPenerbit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextISBN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextEdisi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextKolasi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextJumlah = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextHarga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDeskripsiBuku = new javax.swing.JTextArea();
        jButtonSimpanBuku = new javax.swing.JButton();
        jButtonBatalBuku = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButtonUpdateBook = new javax.swing.JButton();
        jButtonCancelUpdate = new javax.swing.JButton();
        jPanelAbout = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel_input_ddc = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButtonSimpanDDC = new javax.swing.JButton();
        jButtonBatalDDC = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDDC = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jTextKodeDDC = new javax.swing.JTextField();
        jTextNamaDDC = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDeskripsiDDC = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jData_Anggota = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jData_Buku = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jTransaksi = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jCetak = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jBantuan = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALI");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Bukul", "Pengarang", "Penerbit", "Tanggal Terbit", "ISBN", "Edisi", "Kolasi", "Jumlah", "Harga", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuku.getTableHeader().setReorderingAllowed(false);
        jTableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBukuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableBuku);
        if (jTableBuku.getColumnModel().getColumnCount() > 0) {
            jTableBuku.getColumnModel().getColumn(0).setResizable(false);
            jTableBuku.getColumnModel().getColumn(1).setResizable(false);
            jTableBuku.getColumnModel().getColumn(2).setResizable(false);
            jTableBuku.getColumnModel().getColumn(3).setResizable(false);
            jTableBuku.getColumnModel().getColumn(4).setResizable(false);
            jTableBuku.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableBuku.getColumnModel().getColumn(5).setResizable(false);
            jTableBuku.getColumnModel().getColumn(6).setResizable(false);
            jTableBuku.getColumnModel().getColumn(7).setResizable(false);
            jTableBuku.getColumnModel().getColumn(8).setResizable(false);
            jTableBuku.getColumnModel().getColumn(9).setResizable(false);
            jTableBuku.getColumnModel().getColumn(10).setResizable(false);
        }

        jButtonInputBuku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonInputBuku.setText("Input Buku");
        jButtonInputBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputBukuActionPerformed(evt);
            }
        });

        jButtonCariBuku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCariBuku.setText("Cari Buku");
        jButtonCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariBukuActionPerformed(evt);
            }
        });

        jLabel1.setText("   ");

        jButtonHapusBuku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonHapusBuku.setText("Hapus Buku");
        jButtonHapusBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusBukuActionPerformed(evt);
            }
        });

        jButtonUpdateBuku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonUpdateBuku.setText("Update Buku");
        jButtonUpdateBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BukuLayout = new javax.swing.GroupLayout(Buku);
        Buku.setLayout(BukuLayout);
        BukuLayout.setHorizontalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1345, Short.MAX_VALUE)
                    .addGroup(BukuLayout.createSequentialGroup()
                        .addComponent(jButtonInputBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateBuku)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapusBuku)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BukuLayout.setVerticalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jButtonHapusBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUpdateBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonInputBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buku", Buku);

        javax.swing.GroupLayout PeminjamanLayout = new javax.swing.GroupLayout(Peminjaman);
        Peminjaman.setLayout(PeminjamanLayout);
        PeminjamanLayout.setHorizontalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
        );
        PeminjamanLayout.setVerticalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Peminjaman", Peminjaman);

        javax.swing.GroupLayout TransaksiLayout = new javax.swing.GroupLayout(Transaksi);
        Transaksi.setLayout(TransaksiLayout);
        TransaksiLayout.setHorizontalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
        );
        TransaksiLayout.setVerticalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Transaksi", Transaksi);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 630));

        javax.swing.GroupLayout jPanel_input_anggotaLayout = new javax.swing.GroupLayout(jPanel_input_anggota);
        jPanel_input_anggota.setLayout(jPanel_input_anggotaLayout);
        jPanel_input_anggotaLayout.setHorizontalGroup(
            jPanel_input_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jPanel_input_anggotaLayout.setVerticalGroup(
            jPanel_input_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_input_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 500));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabelInputBuku.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelInputBuku.setText("Input Data Buku");

        jLabel2.setText("Menu ini digunakan untuk memasukan data buku yang ada di perpustakaan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelInputBuku))
                .addContainerGap(866, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInputBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Input Data Buku");

        jLabel5.setText("Kode Buku");

        jTextKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKodeBukuActionPerformed(evt);
            }
        });

        jLabel6.setText("Judul Buku");

        jLabel7.setText("Pengarang");

        jLabel8.setText("Penerbit");

        jTextPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPenerbitActionPerformed(evt);
            }
        });

        jLabel9.setText("Tanggal Terbit");

        jLabel10.setText("ISBN");

        jLabel11.setText("Edisi");

        jLabel12.setText("Kolasi");

        jLabel14.setText("Jumlah");

        jLabel15.setText("Harga");

        jLabel16.setText("Deskripsi");

        jTextDeskripsiBuku.setColumns(20);
        jTextDeskripsiBuku.setRows(5);
        jScrollPane1.setViewportView(jTextDeskripsiBuku);

        jButtonSimpanBuku.setText("Simpan");
        jButtonSimpanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanBukuActionPerformed(evt);
            }
        });

        jButtonBatalBuku.setText("Batal");
        jButtonBatalBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalBukuActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jDateChooser2.setDateFormatString("yyyy MMM d");

        jButtonUpdateBook.setText("Update");
        jButtonUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateBookActionPerformed(evt);
            }
        });

        jButtonCancelUpdate.setText("Batal");
        jButtonCancelUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_input_bukuLayout = new javax.swing.GroupLayout(jPanel_input_buku);
        jPanel_input_buku.setLayout(jPanel_input_bukuLayout);
        jPanel_input_bukuLayout.setHorizontalGroup(
            jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel_input_bukuLayout.createSequentialGroup()
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_input_bukuLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel_input_bukuLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextISBN)
                            .addComponent(jTextEdisi, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jTextPengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jTextPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jTextKodeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jTextJudulBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createSequentialGroup()
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(75, 75, 75)))
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextKolasi)
                    .addComponent(jTextJumlah)
                    .addComponent(jTextHarga)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSimpanBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateBook)
                .addGap(51, 51, 51)
                .addComponent(jButtonBatalBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelUpdate)
                .addGap(105, 105, 105))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_input_bukuLayout.setVerticalGroup(
            jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_input_bukuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextKolasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_input_bukuLayout.createSequentialGroup()
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextEdisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSimpanBuku)
                        .addComponent(jButtonUpdateBook))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBatalBuku)
                        .addComponent(jButtonCancelUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel_input_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 630));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 674, Short.MAX_VALUE))
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 500));

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel17.setText("Input Data DDC");

        jLabel18.setText("Menu ini digunakan untuk memasukan klasifikasi buku menggunakan Standar DDC");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(837, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Input Data Klasifikasi DDC");

        jLabel20.setText("Kode DDC");

        jLabel21.setText("Judul DDC");

        jButtonSimpanDDC.setText("Simpan");
        jButtonSimpanDDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanDDCActionPerformed(evt);
            }
        });

        jButtonBatalDDC.setText("Batal");
        jButtonBatalDDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalDDCActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jTableDDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode DDC", "Judul DDC", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDDC.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableDDC);
        if (jTableDDC.getColumnModel().getColumnCount() > 0) {
            jTableDDC.getColumnModel().getColumn(0).setResizable(false);
            jTableDDC.getColumnModel().getColumn(1).setResizable(false);
            jTableDDC.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel22.setText("Deskripsi");

        jTextAreaDeskripsiDDC.setColumns(20);
        jTextAreaDeskripsiDDC.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDeskripsiDDC);

        javax.swing.GroupLayout jPanel_input_ddcLayout = new javax.swing.GroupLayout(jPanel_input_ddc);
        jPanel_input_ddc.setLayout(jPanel_input_ddcLayout);
        jPanel_input_ddcLayout.setHorizontalGroup(
            jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                        .addGap(569, 569, 569)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_ddcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_ddcLayout.createSequentialGroup()
                        .addComponent(jButtonSimpanDDC)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonBatalDDC)
                        .addGap(214, 214, 214))
                    .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                        .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel20))
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jTextNamaDDC)
                            .addComponent(jTextKodeDDC))
                        .addGap(120, 120, 120))))
        );
        jPanel_input_ddcLayout.setVerticalGroup(
            jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_input_ddcLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextKodeDDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextNamaDDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel_input_ddcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBatalDDC)
                            .addComponent(jButtonSimpanDDC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_input_ddcLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        getContentPane().add(jPanel_input_ddc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 630));

        jFile.setText("File");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jFile.add(jMenuItemLogin);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jFile.add(jMenuItem2);

        jMenuBar1.add(jFile);

        jData_Anggota.setText("Data Anggota");

        jMenuItem3.setText("Anggota Non-Aktif");
        jData_Anggota.add(jMenuItem3);

        jMenuItem5.setText("Cari Anggota");
        jData_Anggota.add(jMenuItem5);

        jMenuItem6.setText("Input Anggota");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jData_Anggota.add(jMenuItem6);

        jMenuItem10.setText("Hapus Anggota");
        jData_Anggota.add(jMenuItem10);

        jMenuItem11.setText("Ubah Anggota");
        jData_Anggota.add(jMenuItem11);

        jMenuBar1.add(jData_Anggota);

        jData_Buku.setText("Data Buku");

        jMenuItem4.setText("Buku Hilang");
        jData_Buku.add(jMenuItem4);

        jMenuItem12.setText("Cari Buku");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jData_Buku.add(jMenuItem12);

        jMenuItem13.setText("Input Buku");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jData_Buku.add(jMenuItem13);

        jMenuItem14.setText("Input DDC");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jData_Buku.add(jMenuItem14);

        jMenuItem15.setText("Hapus Buku");
        jData_Buku.add(jMenuItem15);

        jMenuItem16.setText("Ketgori Buku");
        jData_Buku.add(jMenuItem16);

        jMenuBar1.add(jData_Buku);

        jTransaksi.setText("Transaksi");

        jMenuItem17.setText("Peminjaman");
        jTransaksi.add(jMenuItem17);

        jMenuItem18.setText("Pengembalian");
        jTransaksi.add(jMenuItem18);

        jMenuBar1.add(jTransaksi);

        jCetak.setText("Cetak");

        jMenuItem19.setText("Buku Belum Kembali");
        jCetak.add(jMenuItem19);

        jMenuItem20.setText("Buku Hilang");
        jCetak.add(jMenuItem20);

        jMenuItem21.setText("Data Anggota");
        jCetak.add(jMenuItem21);

        jMenuItem22.setText("Data Anggota non-aktif");
        jCetak.add(jMenuItem22);

        jMenuItem23.setText("Data Buku");
        jCetak.add(jMenuItem23);

        jMenuItem24.setText("Daftar Peminjaman");
        jCetak.add(jMenuItem24);

        jMenuItem25.setText("Daftar Pengembalian");
        jCetak.add(jMenuItem25);

        jMenuItem26.setText("Pembayaran Denda");
        jCetak.add(jMenuItem26);

        jMenuBar1.add(jCetak);

        jBantuan.setText("Bantuan");

        jMenuItem27.setText("Cara Penggunaan");
        jBantuan.add(jMenuItem27);

        jMenuItem28.setText("Tentang Kami");
        jBantuan.add(jMenuItem28);

        jMenuBar1.add(jBantuan);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
        String[] kolom = {"Kode Buku", "Judul Buku", "Pengarang", "Penerbit", "Tanggal Terbit", "ISBN", "Edisi", "Kolasi", "Jumlah", "Harga", "Deskripsi", "tanggal_input"}; 
    }
    private void loadDataD(){
        String[] kolom = {"Kode DDC", "Nama DDC", "Deskripsi"};
    }
    
    
    private void masuk_data_buku(){
        try{
            DateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            String tanggal = dateformat.format(date);
            jDateChooser2.setDateFormatString(tanggal);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            String tgl_terbit = sdf.format(jDateChooser2.getDate());
            String sql = "insert into buku values('"+jTextKodeBuku.getText()+"', '"+jTextJudulBuku.getText()+"', '"+jTextPengarang.getText()+"', '"+jTextPenerbit.getText()+"', '"+
                    tgl_terbit+"', '"+jTextISBN.getText()+"', '"+jTextEdisi.getText()+"', '"+jTextKolasi.getText()+"', "+jTextJumlah.getText()+","+jTextHarga.getText()+",'"+
                    jTextDeskripsiBuku.getText()+"','"+tanggal+"')";
            db.query(sql);
            fillBookTable();
//            refreshTable();
            JOptionPane.showMessageDialog(null, "Data Buku berhasil dimasukan");
            jPanel_input_buku.setVisible(false);
            jPanel_input_anggota.setVisible(false);
            jTabbedPane1.setVisible(true);
        }catch (Exception e){
            cek_kode();
            e.printStackTrace();
        }
    }
    
    private void setBukuUpdate(){
        try {
            String update= tableModel.getValueAt(jTableBuku.getSelectedRow(), 0).toString();
            BukuModel buku = bukuC.getSatuBuku(update);
            jTextKodeBuku.setText(buku.getKode());
            jTextJudulBuku.setText(buku.getJudul());
            jTextPengarang.setText(buku.getPengarang());
            jTextPenerbit.setText(buku.getPenerbit());
            jDateChooser2.setDate(buku.getTanggalTerbit());
            jTextISBN.setText(buku.getIsbn());
            jTextEdisi.setText(buku.getEdisi());
            jTextKolasi.setText(buku.getKolasi());
            jTextJumlah.setText(buku.getJumlah());
            jTextHarga.setText(buku.getHarga());
            jTextDeskripsiBuku.setText(buku.getDeskripsi());
        } catch (SQLException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void update(){
        try {
            DateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            String tanggal = dateformat.format(date);
            jDateChooser2.setDateFormatString(tanggal);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            String tgl_terbit = sdf.format(jDateChooser2.getDate());
//            String sql = "select * from buku where Kode_Buku='"+jTextKodeBuku.getText()+"'";
            String sql = "update buku set Judul_Buku='"+jTextJudulBuku.getText()+"',Pengarang='"+jTextPengarang.getText()+
                    "',Penerbit='"+jTextPenerbit.getText()+"',Tanggal_Terbit='"+jDateChooser2.getDateFormatString()+"',ISBN='"+jTextISBN.getText()+"',Edisi='"+jTextEdisi.getText()+
                    "',Kolasi='"+jTextKolasi.getText()+"',Jumlah='"+jTextJumlah.getText()+"',Harga='"+jTextHarga.getText()+"',Deskripsi='"+jTextDeskripsiBuku.getText()+
                    "',tanggal_input='"+tanggal+"' where Kode_Buku='"+jTextKodeBuku.getText()+"'";
            db.query(sql);
            fillBookTable();
            JOptionPane.showMessageDialog(null, "Data Buku berhasil diupdate");
            isUpdate=false;
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    private void hapusBuku(){
        String hps;
        DefaultTableModel tableModel = (DefaultTableModel) jTableBuku.getModel();
        if(jTableBuku.getSelectedRow()==-1){
            if(jTableBuku.getRowCount()==0){
                jLabel1.setText("Table Kosong");
            }else{
                jLabel1.setText("Pilih salah satu tabel");
            }
        }else{
            hps= tableModel.getValueAt(jTableBuku.getSelectedRow(), 0).toString();
            String sql = "delete from buku where buku.Kode_Buku='"+hps+"'";
            int respon = JOptionPane.showConfirmDialog(rootPane, "Anda yakin menghapus "+hps+"?", "Hapus Buku",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respon == JOptionPane.YES_OPTION){
                db.query(sql);
                tableModel.removeRow(jTableBuku.getSelectedRow());
            }else{
                
            }
        }
    }
    public void setKosongInputBuku(){
        jTextKodeBuku.setText(null);
        jTextJudulBuku.setText(null);
        jTextPengarang.setText(null);
        jTextPenerbit.setText(null);
        jDateChooser2.setDate(null);
        jTextISBN.setText(null);
        jTextEdisi.setText(null);
        jTextKolasi.setText(null);
        jTextJumlah.setText(null);
        jTextHarga.setText(null);
        jTextDeskripsiBuku.setText(null);
    }
    
    private void masuk_ddc(){
        try{
            DateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            String tanggal = dateformat.format(date);
            String sql = "insert into ddc values('"+jTextKodeDDC.getText()+"', '"+jTextNamaDDC.getText()+"', '"+jTextAreaDeskripsiDDC.getText()+"', '"+tanggal+"')";
            db.query(sql);
            refreshTableDDC();
        }catch(Exception r){
            r.printStackTrace();
        }
    }
    
    public void setKosongInputDDC(){
        jTextKodeDDC.setText(null);
        jTextNamaDDC.setText(null);
        jTextAreaDeskripsiDDC.setText(null);
    }
    private void cek_kode(){
        try {
            db.stmt.executeQuery("select*from buku where"+"Kode_Buku="+jTextKodeBuku.getText()+"");
            if(db.rs.next()){   
                if(jTextKodeBuku.getText().equals(db.rs.getString("Kode_Buku"))){
                    JOptionPane.showMessageDialog(null, "Sudah tersedia buku dengan kode : "+jTextKodeBuku.getText());
                }
            }else{
                JOptionPane.showMessageDialog(null, "Buku berhasil dimasukan");
            }
        }catch (SQLException es){
            es.printStackTrace();
        }
    }
    private void refreshTable(){
        try {
            BukuModel book = bukuC.getLastBook();
            tableModel.addRow(new String[]{book.getKode(), book.getJudul(), book.getPengarang(), book.getPenerbit(),
            book.getTanggalTerbit().toString(), book.getIsbn(), book.getEdisi(), book.getKolasi(), book.getJumlah(),
            book.getHarga(), book.getHarga()});
            tableModel.fireTableDataChanged();
            notif(tableModel);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private synchronized void notif(TableModel tableModel){
        tableModel.notifyAll();
    }
    
    private void refreshTableDDC(){
        try{
            DDCModel ddc = ddcC.getLastDDC();
            tableModelD.addRow(new String[]{ddc.getNomer_ddc(), ddc.getNama_ddc(), ddc.getDeskripsi()});
            tableModelD.fireTableDataChanged();
            notif(tableModel);
        }catch(SQLException ey){
            ey.printStackTrace();
        }
    }
    
    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        // TODO add your handling code here:
        new FormLogin(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
//        jTabbedPane1.setVisible(false);
//        jPanel_input_anggota.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setVisible(false);
        jPanel_input_anggota.setVisible(false);
        jPanel_input_ddc.setVisible(false);
        jPanelAbout.setVisible(false);
        jPanel_input_buku.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonInputBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputBukuActionPerformed
        // TODO add your handling code here:
        jButtonUpdateBook.setVisible(false);
        jButtonCancelUpdate.setVisible(false);
        jTabbedPane1.setVisible(false);
        jPanel_input_anggota.setVisible(false);
        jPanel_input_ddc.setVisible(false);
        jPanelAbout.setVisible(false);
        jPanel_input_buku.setVisible(true);
    }//GEN-LAST:event_jButtonInputBukuActionPerformed

    private void jButtonCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariBukuActionPerformed
        // TODO add your handling code here:
        new FormCariBuku(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_jButtonCariBukuActionPerformed

    private void jButtonSimpanDDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanDDCActionPerformed
        masuk_ddc();
        setKosongInputDDC();
        jPanel_input_buku.setVisible(false);
        jPanel_input_anggota.setVisible(false);
        jTabbedPane1.setVisible(true);
    }//GEN-LAST:event_jButtonSimpanDDCActionPerformed

    private void jButtonBatalDDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalDDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBatalDDCActionPerformed

    private void jButtonBatalBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalBukuActionPerformed
        // TODO add your handling code here:
        jPanel_input_buku.setVisible(false);
        jPanel_input_anggota.setVisible(false);
        jTabbedPane1.setVisible(true);
    }//GEN-LAST:event_jButtonBatalBukuActionPerformed

    private void jButtonSimpanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanBukuActionPerformed
        // TODO add your handling code here:
//        cek_kode();
        masuk_data_buku();
        setKosongInputBuku();
//        jPanel_input_buku.setVisible(false);
//        jPanel_input_anggota.setVisible(false);
//        jTabbedPane1.setVisible(true);
    }//GEN-LAST:event_jButtonSimpanBukuActionPerformed

    private void jTextPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPenerbitActionPerformed

    private void jTextKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKodeBukuActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new FormCariBuku(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jTableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBukuMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) jTableBuku.getModel();
        jLabel1.setText(tableModel.getValueAt(jTableBuku.getSelectedRow(), 0).toString());
        
    }//GEN-LAST:event_jTableBukuMouseClicked

    private void jButtonHapusBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusBukuActionPerformed
        hapusBuku();
    }//GEN-LAST:event_jButtonHapusBukuActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        jTabbedPane1.setVisible(false);
        jPanel_input_anggota.setVisible(false);
        jPanel_input_buku.setVisible(false);
        jPanelAbout.setVisible(false);
        jPanel_input_ddc.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jButtonUpdateBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateBukuActionPerformed
        if(jTableBuku.getSelectedRow()==-1){
            if(jTableBuku.getRowCount()==0){
                jLabel1.setText("Table Kosong");
            }else{
                jLabel1.setText("Pilih salah satu tabel");
            }
        }else{
            isUpdate=true;
            jLabelInputBuku.setText("Update Data Buku");
            jTabbedPane1.setVisible(false);
            jPanel_input_anggota.setVisible(false);
            jPanel_input_ddc.setVisible(false);
            jPanelAbout.setVisible(false);
            jPanel_input_buku.setVisible(true);
            jButtonSimpanBuku.setVisible(false);
            jButtonBatalBuku.setVisible(false);
            jButtonUpdateBook.setVisible(true);
            jButtonCancelUpdate.setVisible(true);
            setBukuUpdate();   
        }
    }//GEN-LAST:event_jButtonUpdateBukuActionPerformed

    private void jButtonUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateBookActionPerformed
        // TODO add your handling code here:
        update();
        setKosongInputBuku();
        jTabbedPane1.setVisible(false);
        jPanel_input_anggota.setVisible(false);
        jPanel_input_ddc.setVisible(false);
        jPanelAbout.setVisible(false);
        jPanel_input_buku.setVisible(false);
        jButtonSimpanBuku.setVisible(true);
        jButtonBatalBuku.setVisible(true);
        jLabelInputBuku.setText("Input Data Buku");
        jTabbedPane1.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateBookActionPerformed

    private void jButtonCancelUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jf =new Desktop();
                jf.setVisible(true);
                jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                Dimension dim ;
                dim = Toolkit.getDefaultToolkit().getScreenSize();
 
//                jf.setBounds(0,0,dim.width,dim.height);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buku;
    private javax.swing.JPanel Peminjaman;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JMenu jBantuan;
    private javax.swing.JButton jButtonBatalBuku;
    private javax.swing.JButton jButtonBatalDDC;
    private javax.swing.JButton jButtonCancelUpdate;
    private javax.swing.JButton jButtonCariBuku;
    private javax.swing.JButton jButtonHapusBuku;
    private javax.swing.JButton jButtonInputBuku;
    private javax.swing.JButton jButtonSimpanBuku;
    private javax.swing.JButton jButtonSimpanDDC;
    private javax.swing.JButton jButtonUpdateBook;
    private javax.swing.JButton jButtonUpdateBuku;
    private javax.swing.JMenu jCetak;
    private javax.swing.JMenu jData_Anggota;
    private javax.swing.JMenu jData_Buku;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JMenu jFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInputBuku;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanel_input_anggota;
    private javax.swing.JPanel jPanel_input_buku;
    private javax.swing.JPanel jPanel_input_ddc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTable jTableDDC;
    private javax.swing.JTextArea jTextAreaDeskripsiDDC;
    private javax.swing.JTextArea jTextDeskripsiBuku;
    private javax.swing.JTextField jTextEdisi;
    private javax.swing.JTextField jTextHarga;
    private javax.swing.JTextField jTextISBN;
    private javax.swing.JTextField jTextJudulBuku;
    private javax.swing.JTextField jTextJumlah;
    private javax.swing.JTextField jTextKodeBuku;
    private javax.swing.JTextField jTextKodeDDC;
    private javax.swing.JTextField jTextKolasi;
    private javax.swing.JTextField jTextNamaDDC;
    private javax.swing.JTextField jTextPenerbit;
    private javax.swing.JTextField jTextPengarang;
    private javax.swing.JMenu jTransaksi;
    // End of variables declaration//GEN-END:variables
}
