/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ali;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author om
 */
public class FormCariBuku extends javax.swing.JDialog {

    /**
     * Creates new form FormCariBuku
     */
    public database db;
    public FormCariBuku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        db = new database();
        select();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextCariBuku = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableHasilCari = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\Semester 4\\Proyek Tingkat II\\ALI\\src\\ali\\og.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Cari Data Buku");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Cari Buku");

        jTextCariBuku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRefresh.setText("Muat Ulang");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jTableHasilCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Bukul", "Pengarang", "Penerbit", "Tanggal Terbit", "ISBN", "Edisi", "Kolasi", "Jumlah", "Harga", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableHasilCari);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCari)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRefresh)))
                        .addGap(0, 407, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari)
                    .addComponent(jButtonRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void select(){
        Object header[]= {"Kode_Buku", "Judul_Buku"};
//        Object header[] = {"Kode_Buku", "Judul_Buku", "Pengarang", "Penerbit", "Tanggal_Terbit", "ISBN",
//        "Edisi", "Kolasi", "Jumlah", "Harga", "Deskripsi"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(null, header);
        jTableHasilCari.setModel(defaultTableModel);
        int baris = jTableHasilCari.getRowCount();
        for(int i=0; i<baris; i++){
            defaultTableModel.removeRow(i);
        }
        String sql = "select * from buku";
        try{
            db.stmt = db.conn.createStatement();
            db.rs = db.stmt.executeQuery(sql);
            while(db.rs.next()){
                String kolom1 = db.rs.getString(1);
                String kolom2 = db.rs.getString(2);
//                String kolom3 = db.rs.getString(3);
//                String kolom4 = db.rs.getString(4);
//                String kolom5 = db.rs.getString(5);
//                String kolom6 = db.rs.getString(6);
//                String kolom7 = db.rs.getString(7);
//                String kolom8 = db.rs.getString(8);
//                String kolom9 = db.rs.getString(9);
//                String kolom10 = db.rs.getString(10);
//                String kolom11 = db.rs.getString(11);
                
                String kolom[]={kolom1, kolom2};
//                String kolom[]={kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7, kolom8, kolom9, kolom10, kolom11};
                defaultTableModel.addRow(kolom);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    public void search(String sql){
        String header[] = {"Kode_Buku", "Judul_Buku"};
//        String header[] = {"Kode_Buku", "Judul_Buku", "Pengarang", "Penerbit", "Tanggal_Terbit", "ISBN",
//        "Edisi", "Kolasi", "Jumlah", "Harga", "Deskripsi"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(null, header);
        jTableHasilCari.setModel(defaultTableModel);
        for (int i=0;i<jTableHasilCari.getRowCount(); i++){
            defaultTableModel.removeRow(i);
        }
        try {
            db.stmt = db.conn.createStatement();
            db.rs = db.stmt.executeQuery(sql);
            while(db.rs.next()){
                String kode = db.rs.getString(1);
                String judul = db.rs.getString(2);
                Object baris[] = {kode, judul};
                defaultTableModel.addRow(baris);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void refresh(){
        jTextCariBuku.setText(null);
        Object header[]= {"Kode_Buku", "Judul_Buku"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(null, header);
        jTableHasilCari.setModel(defaultTableModel);
        int baris = jTableHasilCari.getRowCount();
        for(int i=0; i<baris; i++){
            defaultTableModel.removeRow(i);
        }
        String sql = "select * from buku";
        try{
            db.stmt = db.conn.createStatement();
            db.rs = db.stmt.executeQuery(sql);
            while(db.rs.next()){
                String kolom1 = db.rs.getString(1);
                String kolom2 = db.rs.getString(2);
                String kolom[]={kolom1, kolom2};
//                String kolom[]={kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7, kolom8, kolom9, kolom10, kolom11};
                defaultTableModel.addRow(kolom);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String sqlSearch = "select * from buku where Judul_Buku like '%"+jTextCariBuku.getText()+"%'";
        search(sqlSearch);
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        jTextCariBuku.setText(null);
        refresh();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCariBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCariBuku dialog = new FormCariBuku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableHasilCari;
    private javax.swing.JTextField jTextCariBuku;
    // End of variables declaration//GEN-END:variables
}
